// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBORINQK3LpHNZhLhPYxvmYn5PiMKPpnDU',
    appId: '1:950927023271:android:ca7eaeb26d39b29e1d8f82',
    messagingSenderId: '950927023271',
    projectId: 'gim-corpore-sano',
    databaseURL: 'https://gim-corpore-sano-default-rtdb.firebaseio.com',
    storageBucket: 'gim-corpore-sano.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe0qv1BItofVr-DpWxL49G0WJ8AiPa-Tw',
    appId: '1:950927023271:ios:06287502a8c8d2c21d8f82',
    messagingSenderId: '950927023271',
    projectId: 'gim-corpore-sano',
    databaseURL: 'https://gim-corpore-sano-default-rtdb.firebaseio.com',
    storageBucket: 'gim-corpore-sano.appspot.com',
    iosBundleId: 'com.example.gimnasioCorporeSano',
  );
}
